### PR TITLE
Remove known fake numbers

### LINKED ISSUE #6: Fake numbers
Hi all
Just noticed you are getting numbers from sms24.me. That site contains a lot of fake number. (64212524461, 64212524462, etc) so you may want to do something regarding that.

I know because this site scrapes numbers from other sites (including mine) that have disposable numbers. They then put ads on their site and claim the numbers as their own so they make money (A very scummy thing to do). So when they try and scrape my site I have been generating fake number to full their site when it scrapes mine. Just just a little fyi that this list contains a bunch of fake number.

### PR DESCRIPTION
**Pull request by Wikxen**
Resolves #6

### CODE REVIEW

**Comment by brolaugh** [comment]
Won't they just get picked up by the next scrape run?

**Comment by Wikxen** [comment]
> Won't they just get picked up by the next scrape run?

Maybe they will, I got that these were his manual numbers and the other fakes are randomly generated. I don't know if he still posts the manual ones. Ask @jLynx.

This would be permanently solved by #7 and maybe a cleanup with the same validation.

**Comment by jLynx** [comment]
Not longer adding in manual ones. But it looks like its still picking up fake ones like this one which was only added the other day: https://sms24.me/number-462153840016

**Comment by brolaugh** [comment]
> Important to note that these are formatted as real numbers so there is no real way to tell that they are fake unless you call them and you get a disconnected message

Good thing is that Google's phone number library stores metadata about all the number plans of the world so it told me that the number +462153840016 was invalid.

If you want to play with it yourself [here's a link](https://libphonenumber.appspot.com/)

Currently we're adding all numbers that possible numbers but we could "tighten" it a bit by checking if the number matches any numbering plans in #7.

**Comment by jLynx** [comment]
Oh that's quite cool, I'll have a play with it!

**Comment by jLynx** [comment]
A few minutes they just added this one https://sms24.me/number-642145991704 which shows up as real on that site. So just keep that in mind. But still that's a pretty cool tool!

**Comment by brolaugh** [comment]
Thank you for the advice. In that case one would need to do a lookup to see if the number is in active use at which point it becomes very hard to know whether the number is disposable or not.

**Comment by jLynx** [comment]
Tbh it may be easier to just to add all the sites they are stealing numbers from and remove their site as they have no numbers of their own. Usually googling the number shows you the site it originated from. That's how I found out they were stealing my numbers

**Comment by brolaugh** [comment]
> Tbh it may be easier to just to add all the sites they are stealing numbers from and remove their site as they have no numbers of their own.

But then we'd have to chase down all the websites our self and currently sms24.me is doing that for us allowing us to focus on other things. We're primarily using this list to block numbers during our signup process so I'm not sure what benefits there would be to us to find all the originating websites. With that said however, if your viewpoint as a provider of disposable phone numbers is different I'd like to hear it.

**Comment by jLynx** [comment]
I'm perfectly fine with this sort of list and it makes sense in a whole bunch of diffent application. I'm just trying to help out by making it more accurate. At the end of they day, it's run by you and you can handle it how you want to. Yes adding sms24 makes you job easier as they are already scraping numbers from most of the sites on the internet. But the issue is I am feeding them fake data which means this is also collecting fake data which could also potentially contain real numbers of individuals or again just take up space of storing fake numbers. If this is specifically for a website you run, then this may not have much of an impact as the chances of one of your users running into a blocked number they legitimately own is extremely low.

**Comment by brolaugh** [comment]
We're scraping a list of websites for phone numbers so wouldn't you be feeding us fake data too?

**Comment by jLynx** [comment]
Yes that's correct as I said that in my previous post. So that's why I suggested you find the list of other sites that sms24 is using then you won't be getting the fake data that sms24 is illegally scraping from my site and others.

The aim of the game for me is to full that site with as much crap as I can so their users find it unreliable and stop using it. That or they stop illegally scraping my site for numbers and messages. Since there is no way to contact them we just have to wait for them to realise.

**Pull request merged**
